class PointOfInterestsController < ApplicationController
  before_action :set_point_of_interest, only: [:show, :edit, :update, :destroy]

  def index
    @point_of_interests = PointOfInterest.all
  end


  # Those were generated by scaffold, not used yet

  # GET /point_of_interests/1
  def show
  end

  # GET /point_of_interests/new
  def new
    @point_of_interest = PointOfInterest.new
  end

  # GET /point_of_interests/1/edit
  def edit
  end

  # POST /point_of_interests
  def create
    @point_of_interest = PointOfInterest.new(point_of_interest_params)

    if @point_of_interest.save
      redirect_to @point_of_interest, notice: 'Point of interest was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /point_of_interests/1
  def update
    if @point_of_interest.update(point_of_interest_params)
      redirect_to @point_of_interest, notice: 'Point of interest was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /point_of_interests/1
  def destroy
    @point_of_interest.destroy
    redirect_to point_of_interests_url, notice: 'Point of interest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_of_interest
      @point_of_interest = PointOfInterest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def point_of_interest_params
      params[:point_of_interest]
    end
end
